services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.web

    # environment:
    #   - PORT=8002
    #   - DATABASE_URL=postgresql+psycopg://time-user:time-pw@db_service:5432/timescaledb
    env_file:
      - .env

    ports:
      - "8000:8000"
    volumes:
      - ./src:/code:rw

    working_dir: /code
    command: [ "gunicorn", "main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000" ]
    develop:
      watch:
        - action: rebuild
          path: Dockerfile.web
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml
        - action: rebuild
          path: ./src

  db_service:
    image: timescale/timescaledb:2.24.0-pg17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

volumes:
  timescaledb_data:
